[book]
authors = ["community"]
language = "zh-CN"
multilingual = false
src = "src"
title = "Effective Rust 中文翻译"

[output.html]
default-theme = "rust"
additional-css = ["style/css/ferris.css"]
additional-js = ["style/js/ferris.js"]
